dist: xenial
language: python
python: '3.7'
cache:
  pip: true
  directories:
  - "$HOME/.cache/pre-commit"
before_install:
- pip install --upgrade pip==18.1
- pip install pre-commit coveralls poetry
- pre-commit install-hooks
install:
- poetry install -v
script:
- pre-commit run --all-files
- pytest --cov=./marshmallow_sqlalchemy
after_success:
- coveralls -v
before_deploy:
- poetry build -f sdist
deploy:
  provider: script
  script: poetry publish -v --username $PYPI_USER --password $PYPI_PASS
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: LU6C/UGD6ZS7GzBtr4uEf4crafhgiwZBCRBnJdcwMtOihTj36skdTnhlK2mMYNM5ewt//t3m/9zbYPvHgRX2m40yFSbZPXo8IA5KlZKfQlLv0NpZ0UZqCelyWSEpVMP4/R+TCzcUl/wKQA5malDWVOJg/1E1ZDGtvhf8t+sanX8gPeRKKCXgjFhkUmkU0Pv8pei4fzytXUrHmQGgj3eIDwN7Wwyc/WBRV5E0S0R8329fzCP0SiHLFrzncMjjl+qIpM4/7VNx2J2W75QvORXC4MLugptoD4DmM7N3P72hfRl0b1H+7efyAiVsAEzvIzgcXI5528UrW8YjxI61vC1fmcklXS5S25BMKn5nagpAbyfoMrGhuhyQJ6PhtXl8coENTmBrrHgsa6jmMTWffsQvsUqCYGyq32gtWaujYRtpkq5AYZMpu3MaFxEw5GTkEv/BVSxXbaeYRv9574ei8FnMMrvuOA2D66EyAsQh7r+C8AQlFYaNy/7evfs+5iLeGqFfUKGtFIYBefs8W/9Ro8Ck5LwsV+TOfJGHijAjVlL5tKXbcN7sZ8YTQs4DpfLH3uT9lTys351EPG2nfam3gMOSJQwDemKhvyGzfRAJx8PKYRR+nIKTuj1EF9giX4jx5o0Q1hNUOsVfSvm58EbMBm9RRb6sUOMVGAJvVYiX6/WyKD8=
  - secure: ZpUGxK5h22dGDJ1oejp0cCEbXf9BbFxJp9df51TqyHfL6L+19JRxts0rVG6wWpwsXdJYiVF0PswIjlprXMqW/z09nAeQXkda6mXxY+hZp/ssBgz8bW7bzQI74PjD277s2b9ORjEyiQExcdI6u/D/Pe6Qu/pPqT57uyJ3J0fLxLt9RbYaMtNH1kws8Bz6kx6FUJe8aSxxrzhygpcb8wswfr/8K+pJMwPzha5ZzgUtv9wXdjNiFYmtDKhp/MnFwu2Dq3+Tku51iUWJ1134ujw22zXLiefa9J+0tOAfPtZ0bZowcuakxDECwZ/38vL/OPQrf2LieM4a1UGxiDAVkFzv8tmr2obfqeGylAiZ4AAzy8bLwXmUyGVrkGW+ED+yBNuArJ3CC9tjAc9NrwW96ipN85nDRUes/s3kaSHiRr+JpAdCj4Ytplw3jgDYDu1EapAYDj28B4fEkEqvAHT74n8/8SaMcDiZohbJr+F6BDRNz4ZLUuPcL3rW+AJXWegQa0p/7DJMwtPJM+6irMDXUxySsWoPpM9Ao7xUULbISELWIJLlXekuDFcnk2qy3Dp7hHBFcAUy+9rdomFUgQNN0Q7/KupHwoWcGzDn67FLtmyvuGbIhhyu3zRqD++6C4W4ZyqreAbxXLRdVOrlLZATkStPUVR4OzakAzQ2JQ2zlDBgQVo=
